fixtures:
  repositories:
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '1.2.3'
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '2.4.0'
  symlinks:
    haproxy: "#{source_dir}"
