fixtures:
  repositories:
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    haproxy: "#{source_dir}"
